version = 1
description = "Pinned nodes for video, image, and general ComfyUI workflows"

[[node]]
name = "ComfyUI-WanVideoWrapper"
repository = "https://github.com/kijai/ComfyUI-WanVideoWrapper"
commit = "088128b224242e110d3906c6750e9a3a348a659b"

[[node]]
name = "comfyui-florence2"
repository = "https://github.com/kijai/ComfyUI-Florence2"
commit = "9ece3de914214c5f581d725167bc9d0eeb0d1120"

[[node]]
name = "comfyui-frame-interpolation"
repository = "https://github.com/Fannovel16/ComfyUI-Frame-Interpolation"
commit = "26545cc2dd95bc3d27f056016300673bdeee78f5"

[[node]]
name = "comfyui-impact-pack"
repository = "https://github.com/ltdrdata/ComfyUI-Impact-Pack"
commit = "429d0159ad429e64d2b3916e6e7be9c22d025c3c"

[[node]]
name = "comfyui-inpaint-cropandstitch"
repository = "https://github.com/lquesada/ComfyUI-Inpaint-CropAndStitch"
commit = "606e2b4fd83fc44e1f0b403e1f076501db8c3749"

[[node]]
name = "comfyui-kjnodes"
repository = "https://github.com/kijai/ComfyUI-KJNodes"
commit = "3f20054214fec9f9234fd3841ae6f1e4287948f6"

[[node]]
name = "comfyui-videohelpersuite"
repository = "https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite"
commit = "115de7a9d9e34410cffb9ecfd268e993b11a50fb"

[[node]]
name = "comfyui_controlnet_aux"
repository = "https://github.com/Fannovel16/comfyui_controlnet_aux"
commit = "e8b689a513c3e6b63edc44066560ca5919c0576e"

[[node]]
name = "rgthree-comfy"
repository = "https://github.com/rgthree/rgthree-comfy"
commit = "13b4399c00b5ef5a97b1b6800fc1185874740f5d"

[[node]]
name = "was-ns"
repository = "https://github.com/ltdrdata/was-node-suite-comfyui"
commit = "44de705818d4663fefefde57ffe0ea5a9ea39df4"
